backend:
  name: git-gateway
  branch: test

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "about"
    label: "Opis"
    folder: "_description"
    create: false
    fields:
      - { label: "Opis", name: "description", widget: "string"}