backend:
  name: git-gateway
  branch: test

media_folder: "img/uploads"

collections:
  - name: "about"
    label: "O mnie"
    files: 
      - name: "about"
        label: "O mnie"
        file: "about/about.json"
        fields:
          - { label: "Opis", name: "content", widget: "string"}
  - name: "images"
    label: "Images Collection"
    folder: "_images"
    create: true
    fields:
      - name: "image"
        label: "Image"
        widget: "image"